name=input("enter your name")
print("name :",name)
print(type(name))
age=int(input("enter your age"))
print("age:",age)
print(type(age))
id=int(input("enter your id"))
print("id:",id)
print(type(id))
marks=float(input("enter your marks"))
print("marks:",marks)
print(type(marks))